packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@trpc/react-query": ^11.0.0-rc.477
  typescript: ^5.6.3

catalogs:
  react18:
    react: 18.3.1
    react-dom: 18.3.1
    "@types/react": ^18.3.11
    "@types/react-dom": ^18.3.1
